<a href="https://colab.research.google.com/github/chaiyaphum/SuperAI-Engineering-Python-Web-Scraping-Tutorial/blob/main/demo_rid_flow_water.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import requests
import json
import pandas as pd

url = "http://hyd-app.rid.go.th/webservice/SWOCService.svc/getHourlyWaterLevelFromStationCode"

payload = "{\"hydro\":{\"stationcode\":\"N.12A\"}}"

headers = {
  'Host': 'hyd-app.rid.go.th',
  'Referer': 'http://hyd-app.rid.go.th/SVG/flow_water.html?svg=hydro2_636991456217195269',
  'Content-Type': 'application/json',
  'Cookie': 'ASP.NET_SessionId=i3ydj3pnjgg4cky2ctfljgoe',
}

response = requests.request("POST", url, headers=headers, data = payload)

print(response.status_code)

200

In [23]:
print(response.content)

b'[{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":68.680000305175781,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603522800000+0700)\\/","hourlydateString":"24\\/10\\/2020 14:00","indexcount":0,"indexhourlywaterlevel":4615256,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":1.3899999856948853,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":157.89999389648438,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603519200000+0700)\\/","hourlydateString":"24\\/10\\/2020 13:00","indexcount":0,"indexhourlywaterlevel":4614914,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":1.6399999856948853,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":222,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603515600000+0700)\\/","hourlydateString":"24\\/10\\/2020 12:00","indexcount":0,"indexhourlywaterlevel":4614530,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":2.1500000953674316,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":311.70001220703125,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603512000000+0700)\\/","hourlydateString":"24\\/10\\/2020 11:00","indexcount":0,"indexhourlywaterlevel":4614400,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":2.9800000190734863,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":47.569999694824219,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603508400000+0700)\\/","hourlydateString":"24\\/10\\/2020 10:00","indexcount":0,"indexhourlywaterlevel":4614015,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":1.2799999713897705,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":32.919998168945313,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603504800000+0700)\\/","hourlydateString":"24\\/10\\/2020 09:00","indexcount":0,"indexhourlywaterlevel":4613788,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":1.1699999570846558,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":32.919998168945313,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603501200000+0700)\\/","hourlydateString":"24\\/10\\/2020 08:00","indexcount":0,"indexhourlywaterlevel":4613605,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":1.1699999570846558,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":34.040000915527344,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603497600000+0700)\\/","hourlydateString":"24\\/10\\/2020 07:00","indexcount":0,"indexhourlywaterlevel":4612907,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":1.1799999475479126,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":13.3100004196167,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603494000000+0700)\\/","hourlydateString":"24\\/10\\/2020 06:00","indexcount":0,"indexhourlywaterlevel":4612341,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":0.89999997615814209,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":35.200000762939453,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603490400000+0700)\\/","hourlydateString":"24\\/10\\/2020 05:00","indexcount":0,"indexhourlywaterlevel":4612220,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":1.190000057220459,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":37.639999389648438,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603486800000+0700)\\/","hourlydateString":"24\\/10\\/2020 04:00","indexcount":0,"indexhourlywaterlevel":4611840,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":1.2100000381469727,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":41.610000610351563,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603483200000+0700)\\/","hourlydateString":"24\\/10\\/2020 03:00","indexcount":0,"indexhourlywaterlevel":4611641,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":1.2400000095367432,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":50.849998474121094,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603479600000+0700)\\/","hourlydateString":"24\\/10\\/2020 02:00","indexcount":0,"indexhourlywaterlevel":4611368,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":1.2999999523162842,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":75.910003662109375,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603476000000+0700)\\/","hourlydateString":"24\\/10\\/2020 01:00","indexcount":0,"indexhourlywaterlevel":4611202,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":1.4199999570846558,"wlstatus":null,"wlstatusid":0},{"CapacityPercent":null,"Latitude":0,"Longitude":0,"Note":null,"Q":184.30000305175781,"QMax":3000,"WaterlevelValuePercent":null,"ZG":69,"amphurname":"\xe0\xb8\x97\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x9b\xe0\xb8\xa5\xe0\xb8\xb2","braelevel":12.460000038146973,"hourlydate":"\\/Date(1603472400000+0700)\\/","hourlydateString":"24\\/10\\/2020 00:00","indexcount":0,"indexhourlywaterlevel":4610978,"notationString":null,"notationid":0,"provincecode":0,"provincename":"\xe0\xb8\xad\xe0\xb8\xb8\xe0\xb8\x95\xe0\xb8\xa3\xe0\xb8\x94\xe0\xb8\xb4\xe0\xb8\x95\xe0\xb8\x96\xe0\xb9\x8c","stationcode":"N.12A","stationdetail":"\xe0\xb9\x81\xe0\xb8\xa1\xe0\xb9\x88\xe0\xb8\x99\xe0\xb9\x89\xe0\xb8\xb3\xe0\xb8\x99\xe0\xb9\x88\xe0\xb8\xb2\xe0\xb8\x99","stationid":147,"waterlevelvalue":1.7000000476837158,"wlstatus":null,"wlstatusid":0}]'

In [30]:
data_json = json.loads(response.content)

In [41]:
df = pd.DataFrame(data_json)

In [42]:
df

   CapacityPercent  Latitude  Longitude  ... waterlevelvalue  wlstatus  wlstatusid
0             None         0          0  ...            1.39      None           0
1             None         0          0  ...            1.64      None           0
2             None         0          0  ...            2.15      None           0
3             None         0          0  ...            2.98      None           0
4             None         0          0  ...            1.28      None           0
5             None         0          0  ...            1.17      None           0
6             None         0          0  ...            1.17      None           0
7             None         0          0  ...            1.18      None           0
8             None         0          0  ...            0.90      None           0
9             None         0          0  ...            1.19      None           0
10            None         0          0  ...            1.21      None           0
11            None         0          0  ...            1.24      None           0
12            None         0          0  ...            1.30      None           0
13            None         0          0  ...            1.42      None           0
14            None         0          0  ...            1.70      None           0

[15 rows x 24 columns]

In [43]:
df.to_csv('demo_rid_flow_water.csv',index=False, encoding="utf-8")